
interface BlogData {
    formData: BlogPost;
    updateFormData: (key: string, value: any) => void;
  }
  
   // 더미 포스트 데이터
  export const dummyPosts: BlogPost[] = [
    {
      id: 1,
      title: '2024년 주식시장 전망',
      content: '2024년 경제 흐름과 주식시장 분석, 주요 산업의 주식 투자 전략을 제시합니다.',
      date: '2024.10.04',
      imageUrl: '/images/3c.png',
      category: '주식투자',
      likes: 100,
      author: '주식핑',
    },
    {
      id: 2,
      title: '초보자를 위한 주식 투자 가이드',
      content: '주식 투자에 대한 기초 지식을 소개하고 초보자가 피해야 할 실수를 정리합니다.',
      date: '2024.10.04',
      imageUrl: '/path/to/image2.jpg',
      category: '주식투자',
      likes: 98,
      author: '주식핑',
    },
    {
      id: 3,
      title: '배당주 투자, 왜 주목해야 할까?',
      content: '배당주의 특징과 전략을 분석합니다. 안정적인 수익을 추구하는 투자자에게 적합한 종목을 추천합니다.',
      date: '2024.10.04',
      imageUrl: '/path/to/image3.jpg',
      category: '배당주투자',
      likes: 95,
      author: '주식핑',
    },
    {
      id: 4,
      title: '장기 투자 전략 가이드',
      content: '장기적인 주식 투자의 중요성과 전략에 대해 설명합니다.',
      date: '2024.10.03',
      imageUrl: '/path/to/image4.jpg',
      category: '장기투자',
      likes: 85,
      author: '주식핑',
    },
    {
      id: 5,
      title: '초보자를 위한 주식 용어 사전',
      content: '주식 투자 초보자가 알아야 할 주요 용어들을 정리했습니다.',
      date: '2024.10.03',
      imageUrl: '/path/to/image5.jpg',
      category: '주식용어',
      likes: 90,
      author: '주식핑',
    },
    {
      id: 6,
      title: '테크 주식 전망',
      content: '2024년 테크 주식의 전망과 주요 기술 기업들에 대한 분석을 제공합니다.',
      date: '2024.10.02',
      imageUrl: '/path/to/image6.jpg',
      category: '테크주',
      likes: 120,
      author: '주식핑',
    },
    {
      id: 7,
      title: '단기 매매 전략',
      content: '단기 주식 거래 전략을 소개하고, 주식 시장에서 빠른 이익을 얻는 방법을 설명합니다.',
      date: '2024.10.01',
      imageUrl: '/path/to/image7.jpg',
      category: '단기매매',
      likes: 70,
      author: '주식핑',
    },
    {
      id: 8,
      title: '초보자를 위한 재테크 기초',
      content: '주식 외에도 다양한 재테크 기초 지식과 초보자가 알아야 할 사항들을 정리했습니다.',
      date: '2024.09.30',
      imageUrl: '/path/to/image8.jpg',
      category: '재테크',
      likes: 110,
      author: '주식핑',
    },
    {
      id: 9,
      title: '국내외 시장 비교 분석',
      content: '국내 주식 시장과 해외 주식 시장을 비교 분석하여 투자 전략을 세웁니다.',
      date: '2024.09.29',
      imageUrl: '/path/to/image9.jpg',
      category: '시장비교',
      likes: 80,
      author: '주식핑',
    },
  ];
  