name: Create Jira issue task # 1
on: # 2
  issues: 
    types: [opened] 
    
jobs: # 3
  create-issue:  # 4
    name: Create Jira issue # 5
    runs-on: ubuntu-latest # 6
    steps: # 7
    - name:  Login to Jira
      uses: atlassian/gajira-login@v3 # 8
      env: 
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }} # 9
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
    
    - name: Create Issue 
      uses: atlassian/gajira-create@v3
      with:
        project: ${{ secrets.JIRA_PROJECT_KEY }} # 10 - 프로젝트 key
        issuetype: 작업 # 11 - 이슈 타입
        summary: '[FE] ${{ github.event.issue.title }}'
        description: |
          GitHub Issue: ${{ github.event.issue.html_url }}
